spring:
  h2:
    console:
      enabled: true
  datasource:
    name: testds
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      initial-size: 1
      min-idle: 1
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
    schema: classpath*:sql/schema.sql
    data: classpath*:sql/data.sql
  redis:
    database: 0
    password: pass1234
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
mybatis:
  mapper-locations: classpath:orm/*.xml
  type-aliases-package: com.reforgedsrc.app.vue2demo.boot.data.entity