server:
  port: 8080
spring:
  profiles:
    active: dev
logging:
  level:
    org.springframework: INFO
    com.wiz.app.vue2.boot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"