server:
  port: 8080
spring:
  profiles:
    active: dev
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.reforgedsrc.app.vue2demo.boot.data.dao: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"